### ISSUE TITLE
I'm having problem with this thing

### ISSUE THREAD

**Issue by ghost** [TheLegendofPiratesOnline/discord-bot#1]
I go to base folder and clicked BotStart it open up and then it closed fast. Since I don't see any error just the emply black screen and then closed for some reason. 

My python version are 3.6.4

What with the requirements.txt?

I don't know how to install that requirements.txt

Explain the code pls

Also you really need to give us a explain or we don't know how to do this thing. But I prefer using node.js

**Comment by mfwass** [comment]
There are a few required Python packages in order to use this code.  Admittedly, we haven't gotten around to documenting the installation process.  I'm going to generalize this reply so anyone else can read this later on down the line and get a full understanding of how to install it.

In order install the requirements, you must have Python 3 installed.  To download this, go to [Python's download page](https://www.python.org/downloads/) and select the latest version of Python 3.  After downloading and installing Python 3, please do the following:

1. Open a new instance of Terminal or Command Prompt, depending on your operating system.
2. Change your directory to the TLOPO discord bot source code.
3. Run the following command to install the dependencies:
```python3 -m pip install -r requirements.txt```
4. Start the discord bot by running
```python3 -m bot.core.BotStart```
5. On your first start up, you will be asked to configure your bot.  The questions should be very straight forward requiring very little explanation.  If there is something needing additional configuration, please be sure to edit the `settings.json` file in the top-level directory where appropriate.

If all steps were done correctly, you should have an output similar to the following:
<img width="496" alt="screen shot 2018-02-16 at 9 14 26 pm" src="https://user-images.githubusercontent.com/8769835/36337176-819016d6-135e-11e8-887d-113837bb297c.png">

Please let me know if this helps.  If you have any trouble along the way feel free to send another reply.

**Comment by ghost** [comment]
Thank you.

Does it auto-post when jolly roger or queen anne come in?

**Comment by mfwass** [comment]
Not at this time, however that is a planned functionality.  Keep checking out this repository for more updates.  Hope the bot is useful!
